---
- name: Set up cron job for system updates
  hosts: web_server
  become: yes
  
  tasks:
    - name: Schedule system update
      cron:
        name: "system update"
        minute: "0"
        hour: "3"  # Runs at 3 AM daily
        job: "ansible-playbook /mnt/d/Ansible/system_update.yml"
        user: "vagrant"


